### ISSUE TITLE
openapi support ?

### ISSUE THREAD

**Issue by zhenizhui** [gogoyqj/auto-service#27]
hi~, thanks for this tool, it's very helpful to me! 

but i got some error when i'm using this tool with openapi

run this command

```
> npx autos --quiet --models
```

and got the following error: 

```
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:747)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

the api.json looks like this:

```
{
  "openapi": "3.0.3",
  "info": {
    "title": "中台微服务-接口文档",
    "description": "中台微服务",
    "version": "1.0"
  },
  "server": {
     // .....
   },
   "tags": {
     // ....
    },
   "paths": {
     // ....
    },
   "components": {
     // ....
    },
}
```

Looking forward to your reply :)

**Comment by gogoyqj** [comment]
@zhenizhui 目前仅支持 openapi 2，可以让后端把 swagger 版本降低到 v2
